import type { Section } from "@/lib/types";

export const initialSections: Section[] = [
  {
    id: 1,
    type: "text",
    tag: "h1",
    align: "center",
    text: "Hi there 👋",
  },
  {
    id: 2,
    type: "badges",
    align: "center",
    list: [
      { id: 1, label: "Linkedin", message: "treatwashere", color: "blue" },
      {
        id: 2,
        label: "Email",
        message: "treatwashere@gmail.com",
        color: "red",
      },
      {
        id: 3,
        label: "Website",
        message: "https://gitprofile-phi.vercel.app/",
        color: "darkgreen",
      },
    ],
  },
  {
    id: 3,
    type: "text",
    tag: "p",
    align: "center",
    text: "I am a Software Engineer specialising in Frontend Development with 7+ years of experience in building web apps. I have had the opportunity of collaborating with diverse businesses, companies, and agencies worldwide since 2018.",
  },
  {
    id: 4,
    type: "stack",
    align: "center",
    size: 40,
    list: [
      {
        name: "javascript",
        selected: "original",
        versions: ["original", "plain"],
      },
      { name: "html5", selected: "original", versions: ["original", "plain"] },
      { name: "css3", selected: "original", versions: ["original", "plain"] },
      { name: "sass", selected: "original", versions: ["original", "plain"] },
      {
        name: "typescript",
        selected: "original",
        versions: ["original", "plain"],
      },
      { name: "nodejs", selected: "original", versions: ["original", "plain"] },
      { name: "vitejs", selected: "original", versions: ["original", "plain"] },
      { name: "react", selected: "original", versions: ["original", "plain"] },
      { name: "nextjs", selected: "original", versions: ["original", "plain"] },
      { name: "svelte", selected: "original", versions: ["original", "plain"] },
      { name: "docker", selected: "original", versions: ["original", "plain"] },
    ],
  },
  {
    id: 5,
    type: "trophies",
    username: "treatwashere",
    align: "center",
    theme: "dracula",
    title: [
      "Commits",
      "Reviews",
      "Experience",
      "Issues",
      "PullRequest",
      "Stars",
      "Repositories",
      "Followers",
    ],
    rank: ["SECRET", "SSS", "SS", "S", "AAA", "AA", "A"],
    column: 5,
    row: 1,
    marginW: 8,
    marginH: 8,
    bg: true,
    frame: true,
  },
];
